{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fsn.cauly",
    "module": "cauly-sdk",
    "version": "3.5.40",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "realReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cauly-sdk-3.5.40.aar",
          "url": "cauly-sdk-3.5.40.aar",
          "size": 776025,
          "sha512": "5d9fa219b72466edefb512453977de6be8ea5de1dbbb100cd720ed0fc7addeeec886e42b988630e27ddb34225a796bb4f028da1348939da75c578529e168b8dd",
          "sha256": "b952e9db460d1bc18df1676dd9325b2479b58f16a85e991937f7b1e0fb6c1a5e",
          "sha1": "3a5b2d9690b665431443a82267114ed55f81e9d7",
          "md5": "4fcfcf0edd96ae5265521421a4f61e67"
        }
      ]
    },
    {
      "name": "realReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cauly-sdk-3.5.40.aar",
          "url": "cauly-sdk-3.5.40.aar",
          "size": 776025,
          "sha512": "5d9fa219b72466edefb512453977de6be8ea5de1dbbb100cd720ed0fc7addeeec886e42b988630e27ddb34225a796bb4f028da1348939da75c578529e168b8dd",
          "sha256": "b952e9db460d1bc18df1676dd9325b2479b58f16a85e991937f7b1e0fb6c1a5e",
          "sha1": "3a5b2d9690b665431443a82267114ed55f81e9d7",
          "md5": "4fcfcf0edd96ae5265521421a4f61e67"
        }
      ]
    }
  ]
}
