{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fsn.cauly",
    "module": "cauly-sdk",
    "version": "3.5.40",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "realReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cauly-sdk-3.5.40.aar",
          "url": "cauly-sdk-3.5.40.aar",
          "size": 776025,
          "sha512": "06b625ec80586aa1cbb6918d8e6d9267e58f900fab97ffed2b569951fb16a81781f033fc0f00bcce5a1e41d3e4accdf070e6c584f5985d0444bae85bdb60a5b9",
          "sha256": "42ebe640d089f9327f46b19981104a312f8fc11d31dc11c5c2dc7ab757deaa5f",
          "sha1": "030a480b5a893bc3f32fcf58ea011bd5e4a95f9c",
          "md5": "9a3119e8f7524712d2d68e1acd1a99e4"
        }
      ]
    },
    {
      "name": "realReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cauly-sdk-3.5.40.aar",
          "url": "cauly-sdk-3.5.40.aar",
          "size": 776025,
          "sha512": "06b625ec80586aa1cbb6918d8e6d9267e58f900fab97ffed2b569951fb16a81781f033fc0f00bcce5a1e41d3e4accdf070e6c584f5985d0444bae85bdb60a5b9",
          "sha256": "42ebe640d089f9327f46b19981104a312f8fc11d31dc11c5c2dc7ab757deaa5f",
          "sha1": "030a480b5a893bc3f32fcf58ea011bd5e4a95f9c",
          "md5": "9a3119e8f7524712d2d68e1acd1a99e4"
        }
      ]
    }
  ]
}
