{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fsn.cauly",
    "module": "cauly-sdk",
    "version": "3.5.29",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "normalReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cauly-sdk-3.5.29.aar",
          "url": "cauly-sdk-3.5.29.aar",
          "size": 770597,
          "sha512": "e0872e9ca140ceb8e74f86ab5558b8315bd6e68a6da1f1fb1e38eca3cd38b63e7b3abc19c9b3b01779a86ba28f11d21b9445cb60dcd965571926781e7622ba16",
          "sha256": "09427be2c5ac6fb1f1e342c3bcf789693000eedbf4adf943ec3883700c4b6431",
          "sha1": "2fad83972dafbf60b095f227ce0981d97ec9d86e",
          "md5": "bc3bb221945a651d7c3a3307be40d0f8"
        }
      ]
    },
    {
      "name": "normalReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cauly-sdk-3.5.29.aar",
          "url": "cauly-sdk-3.5.29.aar",
          "size": 770597,
          "sha512": "e0872e9ca140ceb8e74f86ab5558b8315bd6e68a6da1f1fb1e38eca3cd38b63e7b3abc19c9b3b01779a86ba28f11d21b9445cb60dcd965571926781e7622ba16",
          "sha256": "09427be2c5ac6fb1f1e342c3bcf789693000eedbf4adf943ec3883700c4b6431",
          "sha1": "2fad83972dafbf60b095f227ce0981d97ec9d86e",
          "md5": "bc3bb221945a651d7c3a3307be40d0f8"
        }
      ]
    }
  ]
}
