{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fsn.cauly",
    "module": "cauly-sdk",
    "version": "3.5.30",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "normalReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cauly-sdk-3.5.30.aar",
          "url": "cauly-sdk-3.5.30.aar",
          "size": 770170,
          "sha512": "3617c51df0db4ec3d79625121d442583d9284e61f84343990e79876ac905a9c05a64158381feba23c5c605c5abbc994f3ba2e299623331e2271f0f165c23438a",
          "sha256": "fe21291c87f6cf52fc5209d95ed00da4f89e2384b2b8051f65d27388a58892ae",
          "sha1": "5ed9a8b50af0988cd33c6d59f58e0454351000b7",
          "md5": "52436cc7d2236dbe4c640ad0330aca46"
        }
      ]
    },
    {
      "name": "normalReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cauly-sdk-3.5.30.aar",
          "url": "cauly-sdk-3.5.30.aar",
          "size": 770170,
          "sha512": "3617c51df0db4ec3d79625121d442583d9284e61f84343990e79876ac905a9c05a64158381feba23c5c605c5abbc994f3ba2e299623331e2271f0f165c23438a",
          "sha256": "fe21291c87f6cf52fc5209d95ed00da4f89e2384b2b8051f65d27388a58892ae",
          "sha1": "5ed9a8b50af0988cd33c6d59f58e0454351000b7",
          "md5": "52436cc7d2236dbe4c640ad0330aca46"
        }
      ]
    }
  ]
}
