{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fsn.cauly",
    "module": "cauly-sdk",
    "version": "3.5.39",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "normalReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cauly-sdk-3.5.39.aar",
          "url": "cauly-sdk-3.5.39.aar",
          "size": 787365,
          "sha512": "6913025554dd7e4bc10cc5b6defa8d8a079d0790523cd5b96416682043eb56ec6ccdbee5b3dbd8d1ac84518ece8d001ee232b443673ddea968242d7d0f3413e2",
          "sha256": "21656e0bf74855e6956a406e3f566d85cf9b1601da344ed100737947a5575446",
          "sha1": "8732a74be04259a7c4c8d1c5166bf319504ce6d8",
          "md5": "a0c27f69360d907a5c647b5dc55fab41"
        }
      ]
    },
    {
      "name": "normalReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cauly-sdk-3.5.39.aar",
          "url": "cauly-sdk-3.5.39.aar",
          "size": 787365,
          "sha512": "6913025554dd7e4bc10cc5b6defa8d8a079d0790523cd5b96416682043eb56ec6ccdbee5b3dbd8d1ac84518ece8d001ee232b443673ddea968242d7d0f3413e2",
          "sha256": "21656e0bf74855e6956a406e3f566d85cf9b1601da344ed100737947a5575446",
          "sha1": "8732a74be04259a7c4c8d1c5166bf319504ce6d8",
          "md5": "a0c27f69360d907a5c647b5dc55fab41"
        }
      ]
    }
  ]
}
