{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fsn.cauly",
    "module": "cauly-sdk",
    "version": "3.5.32",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "normalReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cauly-sdk-3.5.32.aar",
          "url": "cauly-sdk-3.5.32.aar",
          "size": 770747,
          "sha512": "c70e7fbb8f0191afcd27f088a9e5fd6f10bd0c1747cbe5da86eb16d19445bb967eb47fa74d927a551906811aff7aa9c4429b0c7d56acf87ef062c54eeb60050e",
          "sha256": "9b4a57ca5228359d7e0ca8a75ac4b51e218903f465c882d8212ceb981e25b4e4",
          "sha1": "7916b57c6be2ac0984eafcbd5e3321bbc1b93f9b",
          "md5": "341a8e741987a8f565ee0fa91d7079ea"
        }
      ]
    },
    {
      "name": "normalReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cauly-sdk-3.5.32.aar",
          "url": "cauly-sdk-3.5.32.aar",
          "size": 770747,
          "sha512": "c70e7fbb8f0191afcd27f088a9e5fd6f10bd0c1747cbe5da86eb16d19445bb967eb47fa74d927a551906811aff7aa9c4429b0c7d56acf87ef062c54eeb60050e",
          "sha256": "9b4a57ca5228359d7e0ca8a75ac4b51e218903f465c882d8212ceb981e25b4e4",
          "sha1": "7916b57c6be2ac0984eafcbd5e3321bbc1b93f9b",
          "md5": "341a8e741987a8f565ee0fa91d7079ea"
        }
      ]
    }
  ]
}
