{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fsn.cauly",
    "module": "cauly-sdk",
    "version": "3.5.47",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "realReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cauly-sdk-3.5.47.aar",
          "url": "cauly-sdk-3.5.47.aar",
          "size": 826163,
          "sha512": "17d275f2b5b180c697328a6d36929fc97d144c51c4be068c92b186444ce481ea346bb6d3ef1ff0b150a1804852b31899e6332523091857844f585aa5d820519f",
          "sha256": "17e8115e138ab74cb50fb2ae21d76c9cb9b214ab0c7ec3aefcfe013cb1436dfe",
          "sha1": "780e7623466b548003a48aa93fa4f8701c35a874",
          "md5": "55248ea8a99f73e13497464c9059a2ab"
        }
      ]
    },
    {
      "name": "realReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cauly-sdk-3.5.47.aar",
          "url": "cauly-sdk-3.5.47.aar",
          "size": 826163,
          "sha512": "17d275f2b5b180c697328a6d36929fc97d144c51c4be068c92b186444ce481ea346bb6d3ef1ff0b150a1804852b31899e6332523091857844f585aa5d820519f",
          "sha256": "17e8115e138ab74cb50fb2ae21d76c9cb9b214ab0c7ec3aefcfe013cb1436dfe",
          "sha1": "780e7623466b548003a48aa93fa4f8701c35a874",
          "md5": "55248ea8a99f73e13497464c9059a2ab"
        }
      ]
    }
  ]
}
