{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fsn.cauly",
    "module": "cauly-sdk-uat",
    "version": "3.5.44",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cauly-sdk-uat-3.5.44.aar",
          "url": "cauly-sdk-uat-3.5.44.aar",
          "size": 956407,
          "sha512": "f3e103caefbc6d1c6483e5c663b72c2dca9e9e1ee4e02977411de16af4a5ba24eebb067481801bb822157de8caee3793d5fa9894c4352483f285652bc5615c44",
          "sha256": "4d6bf5d49380480946c52f855a3d0942ae6d4ca1c750b74e7cb7e23e0d20bcff",
          "sha1": "fd6ff8e15cb943e65d950b4b70cc5705873c8162",
          "md5": "de79d0af156a4220aec24f695a88ca4c"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cauly-sdk-uat-3.5.44.aar",
          "url": "cauly-sdk-uat-3.5.44.aar",
          "size": 956407,
          "sha512": "f3e103caefbc6d1c6483e5c663b72c2dca9e9e1ee4e02977411de16af4a5ba24eebb067481801bb822157de8caee3793d5fa9894c4352483f285652bc5615c44",
          "sha256": "4d6bf5d49380480946c52f855a3d0942ae6d4ca1c750b74e7cb7e23e0d20bcff",
          "sha1": "fd6ff8e15cb943e65d950b4b70cc5705873c8162",
          "md5": "de79d0af156a4220aec24f695a88ca4c"
        }
      ]
    }
  ]
}
