{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fsn.cauly",
    "module": "cauly-sdk-uat",
    "version": "3.5.44",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cauly-sdk-uat-3.5.44.aar",
          "url": "cauly-sdk-uat-3.5.44.aar",
          "size": 956318,
          "sha512": "6db86067393072a0aac8b9578f4f59c7f82b8aae64623e563b551ca1acb7da66fc52458b97ce93f6164b063af5a213eae046dbcd829f9c0ddc934a89f9482178",
          "sha256": "8e6bd4fd84559e013b71d61258e6f268c1086bb03d81676a15f60079cefc7995",
          "sha1": "fdd74707c6c45d591f974ef505881d28304cbf38",
          "md5": "ab0bfc11b79c15d7efed516e8b5af9d2"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cauly-sdk-uat-3.5.44.aar",
          "url": "cauly-sdk-uat-3.5.44.aar",
          "size": 956318,
          "sha512": "6db86067393072a0aac8b9578f4f59c7f82b8aae64623e563b551ca1acb7da66fc52458b97ce93f6164b063af5a213eae046dbcd829f9c0ddc934a89f9482178",
          "sha256": "8e6bd4fd84559e013b71d61258e6f268c1086bb03d81676a15f60079cefc7995",
          "sha1": "fdd74707c6c45d591f974ef505881d28304cbf38",
          "md5": "ab0bfc11b79c15d7efed516e8b5af9d2"
        }
      ]
    }
  ]
}
