{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fsn.cauly",
    "module": "cauly-sdk-uat",
    "version": "3.5.47",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cauly-sdk-uat-3.5.47.aar",
          "url": "cauly-sdk-uat-3.5.47.aar",
          "size": 995699,
          "sha512": "b752af4dd0ee7f0b723d9916ddf957b00b34c55a3d12fd83917b1ade50abe5841bfa31bb6988e12531c8f2a0314f438d2017fbb558bddc512ab28703236b8915",
          "sha256": "37819b487964c2f3e33941350867f37c437a60e1bcc672570ffc1dc4f5483f2b",
          "sha1": "754971d24a76ea1d630db09ab47e123eac310ed8",
          "md5": "47349084c43f8fa033f279e5b36095f1"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cauly-sdk-uat-3.5.47.aar",
          "url": "cauly-sdk-uat-3.5.47.aar",
          "size": 995699,
          "sha512": "b752af4dd0ee7f0b723d9916ddf957b00b34c55a3d12fd83917b1ade50abe5841bfa31bb6988e12531c8f2a0314f438d2017fbb558bddc512ab28703236b8915",
          "sha256": "37819b487964c2f3e33941350867f37c437a60e1bcc672570ffc1dc4f5483f2b",
          "sha1": "754971d24a76ea1d630db09ab47e123eac310ed8",
          "md5": "47349084c43f8fa033f279e5b36095f1"
        }
      ]
    }
  ]
}
