{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fsn.cauly",
    "module": "cauly-sdk-uat",
    "version": "3.5.41",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cauly-sdk-uat-3.5.41.aar",
          "url": "cauly-sdk-uat-3.5.41.aar",
          "size": 932497,
          "sha512": "bd6b3ac029d8a83df1ed1ece2ab3a60440fbd2fc2343bd6caf950e327df0f84267eee0be683e7009b8c087210642d8564074277e35f511b2f109ee9da5feace1",
          "sha256": "90f998bcaa1e7c12543ae8d1f1cd5c6c55321f5aaa62579b3a941f9d98232ed7",
          "sha1": "0a5fe20ef701bc2beaa0fddcd39271a9f83fb4b9",
          "md5": "521065a448482cbd2bbfeb02bec90665"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cauly-sdk-uat-3.5.41.aar",
          "url": "cauly-sdk-uat-3.5.41.aar",
          "size": 932497,
          "sha512": "bd6b3ac029d8a83df1ed1ece2ab3a60440fbd2fc2343bd6caf950e327df0f84267eee0be683e7009b8c087210642d8564074277e35f511b2f109ee9da5feace1",
          "sha256": "90f998bcaa1e7c12543ae8d1f1cd5c6c55321f5aaa62579b3a941f9d98232ed7",
          "sha1": "0a5fe20ef701bc2beaa0fddcd39271a9f83fb4b9",
          "md5": "521065a448482cbd2bbfeb02bec90665"
        }
      ]
    }
  ]
}
