{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fsn.cauly",
    "module": "cauly-sdk-uat",
    "version": "3.5.41",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cauly-sdk-uat-3.5.41.aar",
          "url": "cauly-sdk-uat-3.5.41.aar",
          "size": 933238,
          "sha512": "daedd2c759ed2b9462ea7c3013f69209653f81213681265f266826153c5553d195b85ce2cd5fb9971c6082767e7460ceb8e9525612afefe8e7ece643bc67665f",
          "sha256": "36c708efc9072e42d1fdca9753af1ea452de548e82b0ac79c8beff9df0841b29",
          "sha1": "3caa2934dcffda6b976f14f645512953f2c5dad0",
          "md5": "882d78081eacc4de062f045e2936561b"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cauly-sdk-uat-3.5.41.aar",
          "url": "cauly-sdk-uat-3.5.41.aar",
          "size": 933238,
          "sha512": "daedd2c759ed2b9462ea7c3013f69209653f81213681265f266826153c5553d195b85ce2cd5fb9971c6082767e7460ceb8e9525612afefe8e7ece643bc67665f",
          "sha256": "36c708efc9072e42d1fdca9753af1ea452de548e82b0ac79c8beff9df0841b29",
          "sha1": "3caa2934dcffda6b976f14f645512953f2c5dad0",
          "md5": "882d78081eacc4de062f045e2936561b"
        }
      ]
    }
  ]
}
