{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fsn.cauly",
    "module": "cauly-sdk-uat",
    "version": "3.5.46",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cauly-sdk-uat-3.5.46.aar",
          "url": "cauly-sdk-uat-3.5.46.aar",
          "size": 995522,
          "sha512": "2049b9a84dcaf1b482f360aae6212190b727043a794f748661c5ec7eb289a82dec36e6e23e4f66f9e1a9ddf348882dd53cf1cf589b4dfb1ab1521da202917c91",
          "sha256": "b51ddbf8388edac334f380821829486d69a4746f10fe05197c3747c800fe8121",
          "sha1": "1c42fcc0993b06d7ff4535a5814ba0963b07d6ef",
          "md5": "d20057f332b708fe90841b7d10fc5345"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cauly-sdk-uat-3.5.46.aar",
          "url": "cauly-sdk-uat-3.5.46.aar",
          "size": 995522,
          "sha512": "2049b9a84dcaf1b482f360aae6212190b727043a794f748661c5ec7eb289a82dec36e6e23e4f66f9e1a9ddf348882dd53cf1cf589b4dfb1ab1521da202917c91",
          "sha256": "b51ddbf8388edac334f380821829486d69a4746f10fe05197c3747c800fe8121",
          "sha1": "1c42fcc0993b06d7ff4535a5814ba0963b07d6ef",
          "md5": "d20057f332b708fe90841b7d10fc5345"
        }
      ]
    }
  ]
}
