{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fsn.cauly",
    "module": "cauly-sdk-uat",
    "version": "3.5.46",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cauly-sdk-uat-3.5.46.aar",
          "url": "cauly-sdk-uat-3.5.46.aar",
          "size": 964035,
          "sha512": "613b06c8429cba0bbf2d9d2db378a0a80a8b5aceef26735feb610bcb169ac4da33152a5bce844dc9c4d3d4c84d9bec198e665a88bd42bb423477225dabcb082d",
          "sha256": "ecd40e51d098d5cc25591a66ef70e7b417e78ea083c982f76391e508800fb378",
          "sha1": "39e9b9b1add7890fa2436428abc57f61fc0ed8bb",
          "md5": "e76742608d7392bcec0dbf03d9eeef68"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cauly-sdk-uat-3.5.46.aar",
          "url": "cauly-sdk-uat-3.5.46.aar",
          "size": 964035,
          "sha512": "613b06c8429cba0bbf2d9d2db378a0a80a8b5aceef26735feb610bcb169ac4da33152a5bce844dc9c4d3d4c84d9bec198e665a88bd42bb423477225dabcb082d",
          "sha256": "ecd40e51d098d5cc25591a66ef70e7b417e78ea083c982f76391e508800fb378",
          "sha1": "39e9b9b1add7890fa2436428abc57f61fc0ed8bb",
          "md5": "e76742608d7392bcec0dbf03d9eeef68"
        }
      ]
    }
  ]
}
