{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fsn.cauly",
    "module": "cauly-sdk",
    "version": "3.5.44",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "realReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cauly-sdk-3.5.44.aar",
          "url": "cauly-sdk-3.5.44.aar",
          "size": 793272,
          "sha512": "01fd22b2770597ceca4ab54452a0a51ec6a43f2b3aa091f04a13e777a01047e27eae05b84116575fc55ecdec7a91bb27b66bcc69313af73f48906645b3787777",
          "sha256": "0c8fea819eb3158a52f4d749d89b4d98b52033830629cf37876e483a1b8cfe52",
          "sha1": "e56f94f64b8239b1bb55e6a7234850b030334170",
          "md5": "b103c36ddd49347fb2e31bd44817f4fa"
        }
      ]
    },
    {
      "name": "realReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cauly-sdk-3.5.44.aar",
          "url": "cauly-sdk-3.5.44.aar",
          "size": 793272,
          "sha512": "01fd22b2770597ceca4ab54452a0a51ec6a43f2b3aa091f04a13e777a01047e27eae05b84116575fc55ecdec7a91bb27b66bcc69313af73f48906645b3787777",
          "sha256": "0c8fea819eb3158a52f4d749d89b4d98b52033830629cf37876e483a1b8cfe52",
          "sha1": "e56f94f64b8239b1bb55e6a7234850b030334170",
          "md5": "b103c36ddd49347fb2e31bd44817f4fa"
        }
      ]
    }
  ]
}
