{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fsn.cauly",
    "module": "cauly-sdk-uat",
    "version": "3.5.45",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cauly-sdk-uat-3.5.45.aar",
          "url": "cauly-sdk-uat-3.5.45.aar",
          "size": 956189,
          "sha512": "db7bde5afb568edb932d152f6d34a5a79bd389682fa6c86fef4ce0df65665f6081b2bcd4dd9851196162b4ab20b4775057729fdcd37c06af2c4582a1677bad69",
          "sha256": "d5c6cdb1080b294bbe083cd7de505549c5b440fe4b7c96edba2de1f72c1966e3",
          "sha1": "6158b81bf134da5e6c53ca07237c8718e4d9e279",
          "md5": "8b6e25d9aab501d818bf13e67ccdf136"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cauly-sdk-uat-3.5.45.aar",
          "url": "cauly-sdk-uat-3.5.45.aar",
          "size": 956189,
          "sha512": "db7bde5afb568edb932d152f6d34a5a79bd389682fa6c86fef4ce0df65665f6081b2bcd4dd9851196162b4ab20b4775057729fdcd37c06af2c4582a1677bad69",
          "sha256": "d5c6cdb1080b294bbe083cd7de505549c5b440fe4b7c96edba2de1f72c1966e3",
          "sha1": "6158b81bf134da5e6c53ca07237c8718e4d9e279",
          "md5": "8b6e25d9aab501d818bf13e67ccdf136"
        }
      ]
    }
  ]
}
