{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fsn.cauly",
    "module": "cauly-sdk-uat",
    "version": "3.5.45",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cauly-sdk-uat-3.5.45.aar",
          "url": "cauly-sdk-uat-3.5.45.aar",
          "size": 956023,
          "sha512": "39f8efafbce8cf7bc2cccc0e677324f098aa7a02bcacbf7facb2ab41a8c144437ecabf1089de9d211637bba15ddc2bc817ac9aaf59942d2cfd25d52a39b804a2",
          "sha256": "f9ef6eb34984b93db14d4f3e1fe0bafe3895a933d63bd9e3ad40a5f7b3dd5b42",
          "sha1": "b62b87fe3fc77fe887fdfb98938527c7c0cf9870",
          "md5": "c46d370e1faf79679f85690f13394143"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cauly-sdk-uat-3.5.45.aar",
          "url": "cauly-sdk-uat-3.5.45.aar",
          "size": 956023,
          "sha512": "39f8efafbce8cf7bc2cccc0e677324f098aa7a02bcacbf7facb2ab41a8c144437ecabf1089de9d211637bba15ddc2bc817ac9aaf59942d2cfd25d52a39b804a2",
          "sha256": "f9ef6eb34984b93db14d4f3e1fe0bafe3895a933d63bd9e3ad40a5f7b3dd5b42",
          "sha1": "b62b87fe3fc77fe887fdfb98938527c7c0cf9870",
          "md5": "c46d370e1faf79679f85690f13394143"
        }
      ]
    }
  ]
}
