{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fsn.cauly",
    "module": "cauly-sdk-uat",
    "version": "3.5.45",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cauly-sdk-uat-3.5.45.aar",
          "url": "cauly-sdk-uat-3.5.45.aar",
          "size": 956185,
          "sha512": "5590036d16f892a94f4872181d9f3b5e1beac6b0d90c83b49fb5b878197f2cb19f3c05462784a17d66e490f6909453f31b3ded6fb6486206a8f6807c5df5825b",
          "sha256": "60cc1f7eb8aa262702d8322f0d6611ace0e53295a1888e08e80946d4925b1a36",
          "sha1": "ec77209d1b356c665f86c7ad522a702fd29b3c94",
          "md5": "1be241c69ba76e7d7f6df3f67f64ce9f"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cauly-sdk-uat-3.5.45.aar",
          "url": "cauly-sdk-uat-3.5.45.aar",
          "size": 956185,
          "sha512": "5590036d16f892a94f4872181d9f3b5e1beac6b0d90c83b49fb5b878197f2cb19f3c05462784a17d66e490f6909453f31b3ded6fb6486206a8f6807c5df5825b",
          "sha256": "60cc1f7eb8aa262702d8322f0d6611ace0e53295a1888e08e80946d4925b1a36",
          "sha1": "ec77209d1b356c665f86c7ad522a702fd29b3c94",
          "md5": "1be241c69ba76e7d7f6df3f67f64ce9f"
        }
      ]
    }
  ]
}
