{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fsn.cauly",
    "module": "cauly-sdk",
    "version": "3.5.46",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "realReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cauly-sdk-3.5.46.aar",
          "url": "cauly-sdk-3.5.46.aar",
          "size": 799958,
          "sha512": "22055352c54091fc05e78fe8f9e1c04c383def880d6386f12b16fa21969f4be4dd81d3d1b8b672f40d83c43538109c4f5ff2e4bb9e50a1ff6e9f89065f2f2b17",
          "sha256": "d7fc386c0df4b4ed31f93e7c336cc6579219d138da7c84af44ccee1d77fd8328",
          "sha1": "9a50c0858519a2408f01149f0c995702ff5d3034",
          "md5": "91dad263458950e0c8bae0bf6d4f28a1"
        }
      ]
    },
    {
      "name": "realReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cauly-sdk-3.5.46.aar",
          "url": "cauly-sdk-3.5.46.aar",
          "size": 799958,
          "sha512": "22055352c54091fc05e78fe8f9e1c04c383def880d6386f12b16fa21969f4be4dd81d3d1b8b672f40d83c43538109c4f5ff2e4bb9e50a1ff6e9f89065f2f2b17",
          "sha256": "d7fc386c0df4b4ed31f93e7c336cc6579219d138da7c84af44ccee1d77fd8328",
          "sha1": "9a50c0858519a2408f01149f0c995702ff5d3034",
          "md5": "91dad263458950e0c8bae0bf6d4f28a1"
        }
      ]
    }
  ]
}
