{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fsn.cauly",
    "module": "cauly-sdk",
    "version": "3.5.46",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "realReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cauly-sdk-3.5.46.aar",
          "url": "cauly-sdk-3.5.46.aar",
          "size": 799700,
          "sha512": "3d9140d829fb99e2d9cfac9487b074695b91eb618bea32fd28f82cc599755ed82a482982539221ae302df7ccb4fd406c466896270d33cb6c5c383a18a32dc2ae",
          "sha256": "4699276a239221241cb761c5fb646497f8ef53e14b75ceb192f9c6a8f266e80c",
          "sha1": "7d2e30c9354f4ab8a603dc1e70615891ddf28cff",
          "md5": "f44b8206b13722b6d0aa2209970f98a6"
        }
      ]
    },
    {
      "name": "realReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cauly-sdk-3.5.46.aar",
          "url": "cauly-sdk-3.5.46.aar",
          "size": 799700,
          "sha512": "3d9140d829fb99e2d9cfac9487b074695b91eb618bea32fd28f82cc599755ed82a482982539221ae302df7ccb4fd406c466896270d33cb6c5c383a18a32dc2ae",
          "sha256": "4699276a239221241cb761c5fb646497f8ef53e14b75ceb192f9c6a8f266e80c",
          "sha1": "7d2e30c9354f4ab8a603dc1e70615891ddf28cff",
          "md5": "f44b8206b13722b6d0aa2209970f98a6"
        }
      ]
    }
  ]
}
