{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fsn.cauly",
    "module": "cauly-sdk-uat",
    "version": "3.5.40",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cauly-sdk-uat-3.5.40.aar",
          "url": "cauly-sdk-uat-3.5.40.aar",
          "size": 932469,
          "sha512": "0bb0a7d0feca9dccf08b5da42cd9f5db6e1ee14abda91302a8b5b02fc7a67f956edce72c7082052951c07374a2ac3b5d1d07c1c7fd289addc52fb514abc31216",
          "sha256": "1bfc6b024f9e054a206225ae182ac3ad8cedbbf2313e96e322bbb5deda6178ee",
          "sha1": "423dae40656b03c7999d8ea5691f3af5f2904220",
          "md5": "20a3fca38bfeaf64bf71cd354f31248b"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cauly-sdk-uat-3.5.40.aar",
          "url": "cauly-sdk-uat-3.5.40.aar",
          "size": 932469,
          "sha512": "0bb0a7d0feca9dccf08b5da42cd9f5db6e1ee14abda91302a8b5b02fc7a67f956edce72c7082052951c07374a2ac3b5d1d07c1c7fd289addc52fb514abc31216",
          "sha256": "1bfc6b024f9e054a206225ae182ac3ad8cedbbf2313e96e322bbb5deda6178ee",
          "sha1": "423dae40656b03c7999d8ea5691f3af5f2904220",
          "md5": "20a3fca38bfeaf64bf71cd354f31248b"
        }
      ]
    }
  ]
}
