{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fsn.cauly",
    "module": "cauly-sdk-uat",
    "version": "3.5.40",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cauly-sdk-uat-3.5.40.aar",
          "url": "cauly-sdk-uat-3.5.40.aar",
          "size": 948597,
          "sha512": "72395b51dc8d8529a16ff5701af371bec58e0e3ba746f863c3150de1a933148b1eab09853e4c910669624e22a5060ed1477a74cfc6f5aeceb29b084850ab6269",
          "sha256": "cf7b08a73be8ddfc4855db574c0dffdd7a2c744dbc7ff356aa8e98747c9733c1",
          "sha1": "54918ed1b3bcf3af9d3e035c898af2607de60c69",
          "md5": "367efd59125d1e3361c2ab31bdd72db5"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cauly-sdk-uat-3.5.40.aar",
          "url": "cauly-sdk-uat-3.5.40.aar",
          "size": 948597,
          "sha512": "72395b51dc8d8529a16ff5701af371bec58e0e3ba746f863c3150de1a933148b1eab09853e4c910669624e22a5060ed1477a74cfc6f5aeceb29b084850ab6269",
          "sha256": "cf7b08a73be8ddfc4855db574c0dffdd7a2c744dbc7ff356aa8e98747c9733c1",
          "sha1": "54918ed1b3bcf3af9d3e035c898af2607de60c69",
          "md5": "367efd59125d1e3361c2ab31bdd72db5"
        }
      ]
    }
  ]
}
