{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fsn.cauly",
    "module": "cauly-sdk",
    "version": "3.5.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "4s6gssit5vfejbzhoduu3ugd2q"
    }
  },
  "variants": [
    {
      "name": "normalReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cauly-sdk-3.5.23.aar",
          "url": "cauly-sdk-3.5.23.aar",
          "size": 505025,
          "sha512": "6040921a61e552fd06957fb74160a34d11cf57ed310402c40807a0e03dd888f96c7d992972767228586b133d8e0b393476736dfc1dd2e09db0b947d83ef00f8e",
          "sha256": "e989df71e00ee0f38f92fa78be144d84c16beb0c9e299c643b55636dc4bba0b9",
          "sha1": "d27d695f8915f379683bd82684e641d196531c17",
          "md5": "2a4e8ce198e8113405c89487abe5214b"
        }
      ]
    },
    {
      "name": "normalReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cauly-sdk-3.5.23.aar",
          "url": "cauly-sdk-3.5.23.aar",
          "size": 505025,
          "sha512": "6040921a61e552fd06957fb74160a34d11cf57ed310402c40807a0e03dd888f96c7d992972767228586b133d8e0b393476736dfc1dd2e09db0b947d83ef00f8e",
          "sha256": "e989df71e00ee0f38f92fa78be144d84c16beb0c9e299c643b55636dc4bba0b9",
          "sha1": "d27d695f8915f379683bd82684e641d196531c17",
          "md5": "2a4e8ce198e8113405c89487abe5214b"
        }
      ]
    }
  ]
}
