{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fsn.cauly",
    "module": "cauly-sdk-uat",
    "version": "3.5.43",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cauly-sdk-uat-3.5.43.aar",
          "url": "cauly-sdk-uat-3.5.43.aar",
          "size": 936612,
          "sha512": "0c0a4eca988ed89b3082068f217aeccdfeb3eb8d0be2f74e60af35fb643de3a8f8d096876b9278d31708db49fbc3f0476c8b0530a530ece9e2fd4ae6a9bcbc0a",
          "sha256": "7de69a73e8dd83e2b033ac1fe2f8555201e1321fb0d83e59e0852622be1c4031",
          "sha1": "dc1be131c8c7ad46ddce2e826228aefbfe594735",
          "md5": "fdf55ab3fbe38e5c7531614938be958b"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cauly-sdk-uat-3.5.43.aar",
          "url": "cauly-sdk-uat-3.5.43.aar",
          "size": 936612,
          "sha512": "0c0a4eca988ed89b3082068f217aeccdfeb3eb8d0be2f74e60af35fb643de3a8f8d096876b9278d31708db49fbc3f0476c8b0530a530ece9e2fd4ae6a9bcbc0a",
          "sha256": "7de69a73e8dd83e2b033ac1fe2f8555201e1321fb0d83e59e0852622be1c4031",
          "sha1": "dc1be131c8c7ad46ddce2e826228aefbfe594735",
          "md5": "fdf55ab3fbe38e5c7531614938be958b"
        }
      ]
    }
  ]
}
