{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fsn.cauly",
    "module": "cauly-sdk-uat",
    "version": "3.5.43",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cauly-sdk-uat-3.5.43.aar",
          "url": "cauly-sdk-uat-3.5.43.aar",
          "size": 936500,
          "sha512": "eaab6b1c66dae5b1096cd40a5d0facc1d7b1890678170a62bd7fc2ed094f130133ab091f41c5e2b178f5a5d1646430acd69089733c55aa24da648727a2e629e6",
          "sha256": "a110f35036aab2066a587fe6e4d0545caf205105d212382c4a10512293ceec1b",
          "sha1": "a982825a5d560da44f37a6e4ea4e5ebecf0a4976",
          "md5": "8bd0d59839b86746ecde2e7e558af060"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cauly-sdk-uat-3.5.43.aar",
          "url": "cauly-sdk-uat-3.5.43.aar",
          "size": 936500,
          "sha512": "eaab6b1c66dae5b1096cd40a5d0facc1d7b1890678170a62bd7fc2ed094f130133ab091f41c5e2b178f5a5d1646430acd69089733c55aa24da648727a2e629e6",
          "sha256": "a110f35036aab2066a587fe6e4d0545caf205105d212382c4a10512293ceec1b",
          "sha1": "a982825a5d560da44f37a6e4ea4e5ebecf0a4976",
          "md5": "8bd0d59839b86746ecde2e7e558af060"
        }
      ]
    }
  ]
}
