{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fsn.cauly",
    "module": "cauly-sdk-uat",
    "version": "3.5.43",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cauly-sdk-uat-3.5.43.aar",
          "url": "cauly-sdk-uat-3.5.43.aar",
          "size": 936528,
          "sha512": "a83053f12ac6f03efcebe19a0a8c412a0912ffa8df8d952415cfb6433b05813fc1a97a5222c2694d64535efce5f8fa9b326865772bf5af84d3baaf136286b91b",
          "sha256": "ecde8efe0981b2f40285dbbae67195f4238dabf39763c6d9f9a28e0b4fc03420",
          "sha1": "454bfff10ed54c8d8a531cddb211afa66d028898",
          "md5": "26cc950c514184871176b3d73fe217d7"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cauly-sdk-uat-3.5.43.aar",
          "url": "cauly-sdk-uat-3.5.43.aar",
          "size": 936528,
          "sha512": "a83053f12ac6f03efcebe19a0a8c412a0912ffa8df8d952415cfb6433b05813fc1a97a5222c2694d64535efce5f8fa9b326865772bf5af84d3baaf136286b91b",
          "sha256": "ecde8efe0981b2f40285dbbae67195f4238dabf39763c6d9f9a28e0b4fc03420",
          "sha1": "454bfff10ed54c8d8a531cddb211afa66d028898",
          "md5": "26cc950c514184871176b3d73fe217d7"
        }
      ]
    }
  ]
}
