{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fsn.cauly",
    "module": "cauly-sdk",
    "version": "3.5.33",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "normalReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cauly-sdk-3.5.33.aar",
          "url": "cauly-sdk-3.5.33.aar",
          "size": 771189,
          "sha512": "7f66628cc7c1d0f7366ccf57b6c59b1ef2821edd72e6fa356ed5389460d0a8076cc1531b7e78a8e35ccb426160dd86e3bf37ec091deb4a6d0e56990d256b7924",
          "sha256": "39f803f1ea92147e3512ff5b384ebee012cd22db64541f45ba5616971e2abf69",
          "sha1": "1c4bebf77740dfbda2d3c2ebdcd0547f24feef9e",
          "md5": "584271a4a4c05e409b108b59c18e6dc3"
        }
      ]
    },
    {
      "name": "normalReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cauly-sdk-3.5.33.aar",
          "url": "cauly-sdk-3.5.33.aar",
          "size": 771189,
          "sha512": "7f66628cc7c1d0f7366ccf57b6c59b1ef2821edd72e6fa356ed5389460d0a8076cc1531b7e78a8e35ccb426160dd86e3bf37ec091deb4a6d0e56990d256b7924",
          "sha256": "39f803f1ea92147e3512ff5b384ebee012cd22db64541f45ba5616971e2abf69",
          "sha1": "1c4bebf77740dfbda2d3c2ebdcd0547f24feef9e",
          "md5": "584271a4a4c05e409b108b59c18e6dc3"
        }
      ]
    }
  ]
}
