{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fsn.cauly",
    "module": "cauly-sdk",
    "version": "3.5.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "cdjh3v6ibzaexj546q4b3iwrfu"
    }
  },
  "variants": [
    {
      "name": "normalReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cauly-sdk-3.5.14.aar",
          "url": "cauly-sdk-3.5.14.aar",
          "size": 467819,
          "sha512": "d272edf1c593b56da33b9ce8979e2179ba0f8ff1f246efe2348e6fcea84dc6ee60df0a482e351b32086df40382d7b0cf6af19d860b30f2c37953ddd8f456951d",
          "sha256": "af78d39b0ab75fa9706b1f3d94a928d41458ff2a56545899e9f865cfbb53ee5d",
          "sha1": "b6e57f1d334329b29dc9d60d0461410bfae4012c",
          "md5": "699cea3d160c1702585ecbb21152c0a0"
        }
      ]
    },
    {
      "name": "normalReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "17.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cauly-sdk-3.5.14.aar",
          "url": "cauly-sdk-3.5.14.aar",
          "size": 467819,
          "sha512": "d272edf1c593b56da33b9ce8979e2179ba0f8ff1f246efe2348e6fcea84dc6ee60df0a482e351b32086df40382d7b0cf6af19d860b30f2c37953ddd8f456951d",
          "sha256": "af78d39b0ab75fa9706b1f3d94a928d41458ff2a56545899e9f865cfbb53ee5d",
          "sha1": "b6e57f1d334329b29dc9d60d0461410bfae4012c",
          "md5": "699cea3d160c1702585ecbb21152c0a0"
        }
      ]
    }
  ]
}
