{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fsn.cauly",
    "module": "cauly-sdk",
    "version": "3.5.36",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "normalReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cauly-sdk-3.5.36.aar",
          "url": "cauly-sdk-3.5.36.aar",
          "size": 773289,
          "sha512": "4e7c1325c6afd7764430fd48937637b00a18db52c4f9dc702855602811f0a64004a15ede2a9b83d53e7a069d540f3a54d5f19c12ce5ead2c7ce8c2555f6988f7",
          "sha256": "5d6ec0bf2038b26174264bdc08f61d69db1f796228c82d703bee933cdb1cf477",
          "sha1": "b8071599f72ee86c97c47f061792ff96ae64e149",
          "md5": "4009d03b0bd91dda88bab12130a9016b"
        }
      ]
    },
    {
      "name": "normalReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cauly-sdk-3.5.36.aar",
          "url": "cauly-sdk-3.5.36.aar",
          "size": 773289,
          "sha512": "4e7c1325c6afd7764430fd48937637b00a18db52c4f9dc702855602811f0a64004a15ede2a9b83d53e7a069d540f3a54d5f19c12ce5ead2c7ce8c2555f6988f7",
          "sha256": "5d6ec0bf2038b26174264bdc08f61d69db1f796228c82d703bee933cdb1cf477",
          "sha1": "b8071599f72ee86c97c47f061792ff96ae64e149",
          "md5": "4009d03b0bd91dda88bab12130a9016b"
        }
      ]
    }
  ]
}
