{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fsn.cauly",
    "module": "cauly-sdk-uat",
    "version": "3.5.39",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cauly-sdk-uat-3.5.39.aar",
          "url": "cauly-sdk-uat-3.5.39.aar",
          "size": 351268,
          "sha512": "4281fe7e3064dec7f70159259b7022ede3880a46ea52e2914c34d93f399b7cd461736712b66ece2d948535522a9482577930d5af40ecfc3fc48c67c4704d787d",
          "sha256": "b443317d7c4697a3b29ea1dac5533e4542684f69c37910f713986fae5f318649",
          "sha1": "d7fec030b14aa58ade34dd582ee6d7d8036e028d",
          "md5": "892597ec03307cae23e6391524c6e943"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cauly-sdk-uat-3.5.39.aar",
          "url": "cauly-sdk-uat-3.5.39.aar",
          "size": 351268,
          "sha512": "4281fe7e3064dec7f70159259b7022ede3880a46ea52e2914c34d93f399b7cd461736712b66ece2d948535522a9482577930d5af40ecfc3fc48c67c4704d787d",
          "sha256": "b443317d7c4697a3b29ea1dac5533e4542684f69c37910f713986fae5f318649",
          "sha1": "d7fec030b14aa58ade34dd582ee6d7d8036e028d",
          "md5": "892597ec03307cae23e6391524c6e943"
        }
      ]
    }
  ]
}
