{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fsn.cauly",
    "module": "cauly-sdk-uat",
    "version": "3.5.39",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cauly-sdk-uat-3.5.39.aar",
          "url": "cauly-sdk-uat-3.5.39.aar",
          "size": 944770,
          "sha512": "81b90f75cf293240eb11b8a0bd0f7235162a44334592bcf57678ec4020f4bfb23f6161dea2beac25d34bdb6684ecdd7746fc3d749f93796c921d413f482f1d1f",
          "sha256": "1cdedad6ee37efa396ac39e07643f22883ce1072b32fd4e89a4ef34d54eb02c3",
          "sha1": "49a1d2bca5ab0d03a0c8369f870403227416f750",
          "md5": "6489ac26ad75f77cd958d194150294b8"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cauly-sdk-uat-3.5.39.aar",
          "url": "cauly-sdk-uat-3.5.39.aar",
          "size": 944770,
          "sha512": "81b90f75cf293240eb11b8a0bd0f7235162a44334592bcf57678ec4020f4bfb23f6161dea2beac25d34bdb6684ecdd7746fc3d749f93796c921d413f482f1d1f",
          "sha256": "1cdedad6ee37efa396ac39e07643f22883ce1072b32fd4e89a4ef34d54eb02c3",
          "sha1": "49a1d2bca5ab0d03a0c8369f870403227416f750",
          "md5": "6489ac26ad75f77cd958d194150294b8"
        }
      ]
    }
  ]
}
