{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fsn.cauly",
    "module": "cauly-sdk",
    "version": "3.5.41",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "realReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cauly-sdk-3.5.41.aar",
          "url": "cauly-sdk-3.5.41.aar",
          "size": 777295,
          "sha512": "34a99a891b16dd28786b2a55a931e6bef69c594e355eb69ac7ab3132ae37f9aa9309aa7343e21b88bdca13e5b85ca6491559213152478294b930feb86d15c9f3",
          "sha256": "9d3fbbbec8530591fa5da5446ec89deed16dffb465f1d8523d36426cd24c0908",
          "sha1": "05c88702acc9ecaf88521781613d4abb7c5ebecc",
          "md5": "7b2d40315e927c97027a803f7ebbf753"
        }
      ]
    },
    {
      "name": "realReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cauly-sdk-3.5.41.aar",
          "url": "cauly-sdk-3.5.41.aar",
          "size": 777295,
          "sha512": "34a99a891b16dd28786b2a55a931e6bef69c594e355eb69ac7ab3132ae37f9aa9309aa7343e21b88bdca13e5b85ca6491559213152478294b930feb86d15c9f3",
          "sha256": "9d3fbbbec8530591fa5da5446ec89deed16dffb465f1d8523d36426cd24c0908",
          "sha1": "05c88702acc9ecaf88521781613d4abb7c5ebecc",
          "md5": "7b2d40315e927c97027a803f7ebbf753"
        }
      ]
    }
  ]
}
