{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fsn.cauly",
    "module": "cauly-sdk",
    "version": "3.5.41",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "realReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cauly-sdk-3.5.41.aar",
          "url": "cauly-sdk-3.5.41.aar",
          "size": 776113,
          "sha512": "29aff17fa3c0785bb7d673d387ad5f4802a1881961aba0d4f619162b7f0614c1dff49619c340efb44a35891c7388719b0bb7feb057ab89a75ea16e9e91d38cf4",
          "sha256": "1686ecff9fe5ff08ce9c70d1df3218ce8509ba33902d3bf629887dd28cb79c9a",
          "sha1": "fb0841505569be34beb1a957fa81774f501467c8",
          "md5": "5c9286639669a2edf75a1c02a004a4b4"
        }
      ]
    },
    {
      "name": "realReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cauly-sdk-3.5.41.aar",
          "url": "cauly-sdk-3.5.41.aar",
          "size": 776113,
          "sha512": "29aff17fa3c0785bb7d673d387ad5f4802a1881961aba0d4f619162b7f0614c1dff49619c340efb44a35891c7388719b0bb7feb057ab89a75ea16e9e91d38cf4",
          "sha256": "1686ecff9fe5ff08ce9c70d1df3218ce8509ba33902d3bf629887dd28cb79c9a",
          "sha1": "fb0841505569be34beb1a957fa81774f501467c8",
          "md5": "5c9286639669a2edf75a1c02a004a4b4"
        }
      ]
    }
  ]
}
