{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fsn.cauly",
    "module": "cauly-sdk-uat",
    "version": "3.5.42",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cauly-sdk-uat-3.5.42.aar",
          "url": "cauly-sdk-uat-3.5.42.aar",
          "size": 933090,
          "sha512": "970651a871acec813696f825fe649e4f2037d8dfc5d19ca501c1a72b4b5c3d54586d9e48c79c167cbb9a3bdf12899e26bb0a2d47fb74e9cf8d75338fbbca68b2",
          "sha256": "b1f07e298bdc1aecb47285208ae8caef098be0773147c1b235a11c1378ed90f9",
          "sha1": "ab288ecf962783e30848145e045d73d58b1899c8",
          "md5": "a31268fd1612f4a43c2d7c116ebb23f9"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cauly-sdk-uat-3.5.42.aar",
          "url": "cauly-sdk-uat-3.5.42.aar",
          "size": 933090,
          "sha512": "970651a871acec813696f825fe649e4f2037d8dfc5d19ca501c1a72b4b5c3d54586d9e48c79c167cbb9a3bdf12899e26bb0a2d47fb74e9cf8d75338fbbca68b2",
          "sha256": "b1f07e298bdc1aecb47285208ae8caef098be0773147c1b235a11c1378ed90f9",
          "sha1": "ab288ecf962783e30848145e045d73d58b1899c8",
          "md5": "a31268fd1612f4a43c2d7c116ebb23f9"
        }
      ]
    }
  ]
}
