{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fsn.cauly",
    "module": "cauly-sdk-uat",
    "version": "3.5.42",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cauly-sdk-uat-3.5.42.aar",
          "url": "cauly-sdk-uat-3.5.42.aar",
          "size": 934318,
          "sha512": "c9ad5378ff2eeb9ec6dd4ce67d8f5b54c937493b00097b57466154eb625010935ade2b8f4d61eee9537441e60f59fa4f5293c398cf2849fe1ffa02ecf7085779",
          "sha256": "42b63e03c173e5172615b4259a348fcaccd83cc085a5ef8eb58c722510dd588c",
          "sha1": "f5e293aa9494c6d6f45569578776ce2c6da146e8",
          "md5": "1c55cb1d61a93fdd7687935be0ddbc4c"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cauly-sdk-uat-3.5.42.aar",
          "url": "cauly-sdk-uat-3.5.42.aar",
          "size": 934318,
          "sha512": "c9ad5378ff2eeb9ec6dd4ce67d8f5b54c937493b00097b57466154eb625010935ade2b8f4d61eee9537441e60f59fa4f5293c398cf2849fe1ffa02ecf7085779",
          "sha256": "42b63e03c173e5172615b4259a348fcaccd83cc085a5ef8eb58c722510dd588c",
          "sha1": "f5e293aa9494c6d6f45569578776ce2c6da146e8",
          "md5": "1c55cb1d61a93fdd7687935be0ddbc4c"
        }
      ]
    }
  ]
}
