{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fsn.cauly",
    "module": "cauly-sdk",
    "version": "3.5.45",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "realReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cauly-sdk-3.5.45.aar",
          "url": "cauly-sdk-3.5.45.aar",
          "size": 793157,
          "sha512": "627763a9fe064f2885aa3d1ba1822fbff78d423e94b9625f59468667819a9269d135664e1fc20aa94f7c02a9b4fe37a69a106258ff9b3ad979645d27575092b5",
          "sha256": "fff9f527b48ee2d9d067a097ed4d4171c69e4d94e1ef6a17315a29c0d1c4b1d9",
          "sha1": "62e38631ed9ff074dda6b73b482864a639891773",
          "md5": "4f0a812307cc2d6a1e73ca5d678ff43e"
        }
      ]
    },
    {
      "name": "realReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cauly-sdk-3.5.45.aar",
          "url": "cauly-sdk-3.5.45.aar",
          "size": 793157,
          "sha512": "627763a9fe064f2885aa3d1ba1822fbff78d423e94b9625f59468667819a9269d135664e1fc20aa94f7c02a9b4fe37a69a106258ff9b3ad979645d27575092b5",
          "sha256": "fff9f527b48ee2d9d067a097ed4d4171c69e4d94e1ef6a17315a29c0d1c4b1d9",
          "sha1": "62e38631ed9ff074dda6b73b482864a639891773",
          "md5": "4f0a812307cc2d6a1e73ca5d678ff43e"
        }
      ]
    }
  ]
}
