{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fsn.cauly",
    "module": "cauly-sdk",
    "version": "3.5.45",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "realReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cauly-sdk-3.5.45.aar",
          "url": "cauly-sdk-3.5.45.aar",
          "size": 793447,
          "sha512": "96429c923e975a809b80e2f89e2140cd30c54068954a676bc7ec5f60884fe39c8697f3c75240833a6a56e70220e78e324a197410650d16d41ae2477e802eba8e",
          "sha256": "d803008f78212622829cd4554607bc349759e1784ce0eef4be9e5db6039f68cf",
          "sha1": "868b6ae14b573e3b3f6007b4aa27553d405f28f0",
          "md5": "766518abe56fb7910805c07bcf963459"
        }
      ]
    },
    {
      "name": "realReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cauly-sdk-3.5.45.aar",
          "url": "cauly-sdk-3.5.45.aar",
          "size": 793447,
          "sha512": "96429c923e975a809b80e2f89e2140cd30c54068954a676bc7ec5f60884fe39c8697f3c75240833a6a56e70220e78e324a197410650d16d41ae2477e802eba8e",
          "sha256": "d803008f78212622829cd4554607bc349759e1784ce0eef4be9e5db6039f68cf",
          "sha1": "868b6ae14b573e3b3f6007b4aa27553d405f28f0",
          "md5": "766518abe56fb7910805c07bcf963459"
        }
      ]
    }
  ]
}
