{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fsn.cauly",
    "module": "cauly-sdk",
    "version": "3.5.45",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "realReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cauly-sdk-3.5.45.aar",
          "url": "cauly-sdk-3.5.45.aar",
          "size": 793150,
          "sha512": "0a4095ea08c0184eca89649789f1dba30df32e693b44016eb1c32d0c46be6f4c14df914e09adb394f2baef103dbb63b96980aa5c4d8fcdabd68baa6d38da0f69",
          "sha256": "71efdfecc5b39f09a5bb3ee229f29da016da8f61d0b1e4f9ee9ead39dc26a813",
          "sha1": "7eb0a2afa05475f37dec0f4c2a9db0229f9743d9",
          "md5": "fc53f447c40b02d3146e849c30ff3609"
        }
      ]
    },
    {
      "name": "realReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "cauly-sdk-3.5.45.aar",
          "url": "cauly-sdk-3.5.45.aar",
          "size": 793150,
          "sha512": "0a4095ea08c0184eca89649789f1dba30df32e693b44016eb1c32d0c46be6f4c14df914e09adb394f2baef103dbb63b96980aa5c4d8fcdabd68baa6d38da0f69",
          "sha256": "71efdfecc5b39f09a5bb3ee229f29da016da8f61d0b1e4f9ee9ead39dc26a813",
          "sha1": "7eb0a2afa05475f37dec0f4c2a9db0229f9743d9",
          "md5": "fc53f447c40b02d3146e849c30ff3609"
        }
      ]
    }
  ]
}
